baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Taskcat Workshop"
theme = "learn"
uglyurls = true
#googleAnalytics = "UA-136137356-1"
sectionPagesMenu = "main"
pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "monokai"
publishDir = "docs"



[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "blue"
showVisitedLinks = false
author = "Tony Vattathil"
description = "Taskcat Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true


# [menu]
#   [[menu.main]]
#     identifier = "Prerequisites"
#     name = "This is the Mu track"
#     title = "Workshop using Mu"
#     url = "/mu/"
#     weight = -110

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> taskcat documentation"
identifier = "taskcatio"
url = "https://taskcat.io/"
weight = 20

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> aws-quickstart/taskcat"
identifier = "gitrepo"
url = "https://github.com/aws-quickstart/taskcat"
weight = 30

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
