project:
  name: cfn-project
tests:
  mytest:
    template: templates/lab1.template.yaml
    regions:
    - us-east-1
    parameters:
      S3S3BucketNAme: '$[taskcat_autobucket]'
      S3KeyPrefix: 'cfn-project/'


