# Build your taskcat config here
#
# Note: schema validation is plugged into vscode to provide assistance as you build out your template
# Follow the direction in this section to build you test configuration