name: gensite

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master

    - name: Install  Hugo deps
      run:  sudo apt-get update && sudo apt-get install python-docutils -y 

    - name: Setup Hugo
      run:  HUGO_DEB="$(mktemp)" && wget -O $HUGO_DEB 'https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb' &&  sudo dpkg -i $HUGO_DEB ; rm -f $HUGO_DEB

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.HUGO_GHT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
