name: gensite

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.3
      with:
        hugo-version: '0.58.3'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.HUGO_GHT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
